pss/urls.py
from django.contrib import admin
from django.urls import path, include
from pss_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pss_app.urls')),
    path("accounts/", include("allauth.urls")),
    ]

pss_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .views import(
    ImageFeedView,
    ImageDetailView,
    ImageTagListView,
    ImageCreateView,
    ImageUpdateView,
    ImageDeleteView,
    UserPostList,
    UserImageDetails,
    AddCommentView,
    LikeView,
)

app_name = 'image'

urlpatterns = [
    path('', include("django.contrib.auth.urls")),

    path('', ImageFeedView.as_view(), name='list'),

    path('image/<int:pk>/', ImageDetailView.as_view(), name='detail'),

    path('tag/<slug:tag>/', ImageTagListView.as_view(), name='tag'),

    path('image/create/', ImageCreateView.as_view(), name='create'),

    path('image/<int:pk>/update/', ImageUpdateView.as_view(), name='update'),

    path('image/<int:pk>/delete/', ImageDeleteView.as_view(), name='delete'),

    path('image/user_feed/', UserPostList.as_view(), name="user_feed"),

    path('image/<int:pk>/user_image_details', UserImageDetails.as_view(),
         name='user_image_details'),

    path('photo/<int:pk>/comment/', AddCommentView.as_view(),
         name='add_comment'),

    path('search_results', views.search_results, name='search_results'),

    path('like/<int:pk>', LikeView, name='like_post')
]

templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Add Comment{% endblock %}
{% block content %}

<div class="container pb-2 pt-2 border rounded container-custom my-3">
    <h3>Leave a comment:</h3>
    <p>Posting as: {{ user.username }}</p>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-success mt-2">Add</button>
        </form>
    </div>
    <a class="btn btn-outline-dark" onclick="javascript:history.back()">Exit Without Saving</a></div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="Description" content="A simple photo sharing site where people can share their favourite pictures." />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>
    {% block title %} Home {% endblock %}
 </title>
</head>
<body>
  <a class="skip-link" href="#main">Skip to main</a>
  <header>
    {% if user.is_authenticated %}
    <div class="container-fluid border-bottom ">
      <nav class="navbar navbar-expand-lg navbar-light nav-text">
        <a class="navbar-brand" href="{% url 'image:list' %}">
          <h1 class = "site-title">PHOTO SHARING SITE</h1>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03"
          aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active">Hi {{ user.username }}!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'image:list' %}">Main Feed <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'image:user_feed' %}">My Page</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method=POST action="{% url 'image:search_results' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search Images" aria-label="Search"
              name="searched">
            <button class="btn btn-outline-dark my-2 my-sm-0 mr-2" type="submit">Search</button>
          </form>
          <a class="btn btn-outline-dark my-2 my-sm-0 mr-2" href="{% url 'image:create' %}">Upload Image</a>
          <div class="log-out-button"><a class="btn btn-outline-dark my-2 my-sm-0" href="{% url 'account_logout' %}">Log
              Out</a>
          </div>
      </nav>
    </div>
      {% else %}
    <div class="container-fluid border-bottom">
      <nav class="navbar navbar-expand-lg navbar-light nav-text">
        <a class="navbar-brand" href="{% url 'image:list' %}">
          <h1 class = "site-title">PHOTO SHARING SITE</h1>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03"
          aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Log In <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Sign Up <span class="sr-only"></span></a>
            </li>
          </ul>
        </div>
        {% endif %}
      </nav>  
  </div>
</header>
  <section id = "main" class="pr-3 pl-3 pt-1 pb-1" tabindex="-1" role='main'>
    {% block content %}{% endblock content %}
  </section>

<footer class="container-fluid text-center text-dark border-top border-dark">
  <div class="container p-4 pb-0">
    <section class="mb-2">
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.facebook.com/" target="_blank"
        role="button" aria-label="Link to facebook.com"><i class="fab fa-facebook-f"></i></a>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://twitter.com/" target="_blank" role="button" aria-label="Link to twitter.com"><i
          class="fab fa-twitter"></i></a>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.google.com/" target="_blank" role="button" aria-label="Link to google.com"><i
          class="fab fa-google"></i></a>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.instagram.com/?hl=en" target="_blank"
        role="button" aria-label="Link to instagram.com"><i class="fab fa-instagram"></i></a>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.linkedin.com/" target="_blank"
        role="button" aria-label="Link to linkedin.com"><i class="fab fa-linkedin-in"></i></a>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://github.com/" target="_blank" role="button" aria-label="Link to github.com"><i
          class="fab fa-github"></i></a>
    </section>
    <div class="text-center">
      <p>© 2022 Copyright Photo Sharing Site</p>
    </div>
  </div>
</footer>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  <script src="https://unpkg.com/colcade@0/colcade.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
  {% load static %}
  <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/delete.html
{% extends 'base.html' %}

{% block title %}Delete Image{% endblock %}

{% block content %}
<div class="container pb-2 pt-2 border rounded container-custom my-3">
    <div class="form-group mx-auto">
        <h2 class="text-center">
            You are going to <span class="text-danger">delete</span>: "<i>{{ post.title }}</i>
            "</h2>
        <p class="text-center">Are you sure, you want to delete the photo ?</p>
        <div class="form-group">
            <form action="" method="post" class="d-flex flex-column align-items-center justify-content-center">
                {% csrf_token %}
                <div class="row">
                    <div class="col text-right">
                        <a href="{% url 'image:user_image_details' post.id %}"
                            class="my-2 btn btn-primary btn-sm">Cancel</a>
                    </div>
                    <div class="col text-left">
                        <button type="submit" class="my-2 btn btn-danger btn-sm">Delete</button>
                    </div>
                </div>
                <p>This action is irreversible</p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/feed_public.html
{% extends "base.html" %}

{% block title %}Photo Sharing Site: Home{% endblock %}

{% block content %}
<div id="overlay"></div>
<!-- colcade grid system -->
<div class="row">
    <div class="grid">
        <div class="grid-col grid-col--1"></div>
        <div class="grid-col grid-col--2"></div>
        <div class="grid-col grid-col--3"></div>
        <div class="grid-col grid-col--4"></div>
        {% for photo in photos %}
        <div class="grid-item image-container-custom"><a href="{% url 'image:detail' photo.id %}"> <img
                    src="{{photo.featured_image.url}}" alt="{{photo.title}}" /></a></div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/image_detail.html
{% extends "base.html" %}

{% block title %}{{image.title}} by {{image.author}}{% endblock %}

{% block content %}

{% load crispy_forms_tags %}
<!-- image details section -->
<div class="row mt-2">
    <div class="col-sm-8 pr-2">
        <img class="border rounded" src=" {{ image.featured_image.url }}" alt = "{{ image.title }}">
    </div>
    <div class="col-sm-4 border rounded container-custom">
        <h2 class="image-details-title">{{ image.title }}</h2>
        <hr class="image-details-divder">
    {% if user.is_authenticated  %}
        <div class="d-flex flex-row mb-0">
            <div class="like-btn">
                <form action="{% url 'image:like_post' image.pk %}" method="POST">
                    {% csrf_token %}
                    {% if request.user in image.likes.all %}
                    <div class="d-flex flex-row">
                        <div class="mr-2"><button type="submit" name="image_id" value="{{ image.id }}"
                                class="btn btn-outline-dark btn-sm pt-2" aria-label="like-button">
                                <ion-icon class="" name="heart"></ion-icon>
                            </button>
                        </div>
                        <div>
                            <p class="image-details-content">You have liked this picture.</p>
                        </div>
                    </div>
                    {% else %}
                    <div class="">
                    <button type="submit" name="image_id" value="{{ image.id }}" class="pt-2 btn btn-outline-dark btn-sm">
                        <ion-icon name="heart-outline"></ion-icon>
                    </button>
                    </div>             
                </form>
                {% endif %}
            </div>
        </div>    
            {% else %}
            <p class="image-details-content"><small><i>Please log in to like this image.</i></small>
            {% endif %}
        <hr class="image-details-divder">
        <p class="image-details-content">{{ image.description }}</p>
        <p class="image-details-content"><small>Uploaded by <i>{{ image.author }}</i> on {{ image.created_on }}</small>
        </p>
        <hr class="image-details-divder">
        <div class="num-of-likes">
            <p class="image-details-content">This picture has been liked <strong>{{ image.likes.count }}</strong>
                times.</p>
        </div>
        <hr class="image-details-divder">
        <p class="image-details-content">Image tags:
            {% for tag in image.tags.all %}
            <a href="{% url 'image:tag' tag.slug %}" class="badge badge-pill badge-light p-2">{{tag.name}}</a>,
            {% endfor %}
        </p>
        <hr class="image-details-divder">
    </div>
</div>
<!-- Comments Section -->
<div class="container-fluid pb-2 pt-2 border rounded container-custom mt-3 mb-3">
    <div class="comment-title col-sm">
        <h2>Comments</h2>
    </div>
    {% if user.is_authenticated  %}
    <div class="comments-details pl-3">

        {% if not image.comments.all %}
        <strong>There are no comments yet. Be the first by clicking below!</strong>
        {% else %}
        {% for comment in image.comments.all  %}
        <br>
        <div class="comment-body">
            <strong>{{ comment.body }}</strong>
            <p class="font-italic"><small>Comment added on {{ comment.created_on }} by {{ comment.author }}</small></p>
        </div>
        {% endfor %}
        {% endif %}

    </div>
    <div class="comment-link col-sm mb-3 mt-3"><a class="btn btn-outline-dark"
            href="{% url 'image:add_comment' image.pk %}">Add a
            comment</a></div>
    {% else %}
    <p class="pl-3">You must be logged in to view comments</p>
    {% endif %}
</div>
{%endblock%}

templates/search_results.html
{% extends 'base.html' %}

{% block title %}Search Results{% endblock %}

{% block content %}
<div id="overlay"></div>
{% if searched %}
    <div class="container pb-2 pt-2 border rounded container-custom my-3">
        <h2 class="text-center">Search results for: '{{searched}}'</h2>   
        <div class="row">
            <div class="grid">
                <!-- Colcade Grid System -->
                <div class="grid-col grid-col--1"></div>
                <div class="grid-col grid-col--2"></div>
                <div class="grid-col grid-col--3"></div>
                <div class="grid-col grid-col--4"></div>
                {% for post in posts %}
                <div class="grid-item image-container-custom"><a href="{% url 'image:detail' post.id %}"> <img src="{{ post.featured_image.url }}"
                            alt="{{ post.title }}"></a></div>
                {% empty %}
                <div class="container upload-a-photo mt-2 border-0">
                    <p class="text-center font-italic">There are no images matching your search.<p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% else %}
<div class="container pb-2 pt-2 border rounded container-custom my-3">
    <h2 class="text-center">Please search for an image by entering some information into the search bar above.</h2>
</div>
{% endif %}

{% endblock %}

templates/taglist.html
{% extends 'feed_public.html' %}

{% block title %}{{tag}}: images{% endblock %}

{% block content %}
<div class="container pb-2 pt-2 border rounded container-custom my-3">
    <h2 class="text-center">Photos with the tag '{{tag}}'</h2>
    {{ block.super }}
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block title %}Update Image{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container pb-2 pt-2 border rounded container-custom my-3">
    <div class="mx-auto">
        <h2 class="mt-3 text-center">Edit photo</h2>
    </div>
    <div class="form-group">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success mb-3">Save Changes
            </button>
        </form>
        <a class="btn btn-outline-dark" href="{% url 'image:user_feed' %}">Exit Without Saving</a>
    </div>
</div>
{% endblock %}

templates/upload_image.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Upload Image{% endblock %}

{% block content %}
<div class="container pb-2 pt-2 border rounded container-custom my-3">
    <div class="mx-auto">
        <h2 class="mt-3 text-center">Upload a photo</h2>
    </div>
    <div class="form-group">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success mb-3">Upload Image
            </button>
        </form>
        <a class="btn btn-outline-dark" href="{% url 'image:user_feed' %}">Exit Without Saving</a>
    </div>
</div>
{% endblock %}

templates/user_feed.html
{% extends "base.html" %}

{% block title %}{{user.username}}'s page{% endblock %}

{% block content %}
<div id="overlay"></div>
<div class="row d-flex">
    <div class="user-page-info">
        <p class="lead">This is your private page. Here you will see all of your images (published and drafts).</p>
    </div>
    <div class="row">
        <div class="grid">
            <!-- Colcade Grid System -->
            <div class="grid-col grid-col--1"></div>
            <div class="grid-col grid-col--2"></div>
            <div class="grid-col grid-col--3"></div>
            <div class="grid-col grid-col--4"></div>
            {% for photo in photos %}
            <div class="grid-item image-container-custom"><a href="{% url 'image:user_image_details' photo.id %}">
                    <img src="{{photo.featured_image.url}}" alt="{{photo.title}}" /></a></div>
            {% endfor %}
        </div>
    </div>
</div>
    {% endblock %}

templates/user_image_details.html
{% extends "base.html" %}

{% block title %}{{image.title}} by {{image.author}}{% endblock %}


{% block content %}
<div class="row mt-2">
    <div class="col-sm-8 pr-2">
        <img class="border rounded" src=" {{ image.featured_image.url }}" alt="{{ image.title }}">
    </div>
    <div class="col-sm-4 border rounded container-custom">
        <h2 class="image-details-title">{{ image.title }}</h2>
        <hr class="image-details-divder">
        <div class="text-center">
            {% if image.status == 1 %}
            <p class="text-success">This image has been published to the live feed.</p>
            {% else %}
            <p class="text-danger">This image is still a 'draft' and is visible only to you. </p>
            <p class="text-danger">Comments are disabled until the image is published.</p>
            <p class="text-danger">Click on 'Edit Image' and change the status to 'Published' to publish your image.</p>
            {% endif %}
        </div>
        <hr class="image-details-divder">
        <p class="image-details-content">{{ image.description }}</p>
        <hr class="image-details-divder">
        <p class="image-details-content"><small>Uploaded on {{ image.created_on }}</small></p>
        <div class="num-of-likes">
            <p class="image-details-content">This picture has been liked <strong>{{ image.likes.count }}</strong>
                times.</p>
        </div>
        <hr class="image-details-divder">
        <p class="image-details-content">Image tags:
            {% for tag in image.tags.all %}
            <a href="{% url 'image:tag' tag.slug %}" class="badge badge-pill badge-light p-2">{{tag.name}}</a>,
            {% endfor %}
        </p>
        <hr class="image-details-divder">
        <div class="row d-flex justify-content-between pb-3">
            <p class="image-details-content">Options:
                <div class="d-flex justify-content-center">
                    <a class="btn btn-outline-dark" href="{% url 'image:update' image.pk %}">Edit Image</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a class="btn btn-outline-dark" href="{% url 'image:delete' image.pk %}">Delete Image</a>
                </div>
        </div>
    </div>
</div>
{% if image.status == 1 %}
<div class="container-fluid pb-2 pt-2 border rounded container-custom my-3">
    <div class="comment-title col-sm">
        <h2>Comments</h2>
    </div>
    <div class="comments-details pl-3">
        {% if not image.comments.all %}
        <strong>There are no comments yet. Be the first by clicking below!</strong>
        {% else %}
        {% for comment in image.comments.all  %}
        <br>
        <div class="comment-body">
            <strong>{{ comment.body }}</strong>
            <p class="font-italic"><small>Comment added on {{ comment.created_on }} by {{ comment.author }}</small></p>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="comment-link col-sm mb-3 mt-3"><a class="btn btn-outline-dark"
            href="{% url 'image:add_comment' image.pk %}">Add a
            comment</a></div>
</div>
{% else %}
{% endif %}
{% endblock %}